project_id = "xjeballtxihphcahksuh"

[functions.chat]
verify_jwt = false

[functions.summarize-report]
verify_jwt = false

[functions.notify-admin-signup]
verify_jwt = false

[functions.fetch-stock-prices]
verify_jwt = false

[functions.fetch-market-indices]
verify_jwt = false

[functions.stock-pick-news]
verify_jwt = false

[functions.send-newsletter]
verify_jwt = false

[functions.market-news]
verify_jwt = false